# Download offline package
download:
  # 离线包系统架构, 支持 amd64 和 arm64
  arch: amd64
  # 离线包保存目录，节点安装包从该目录拷贝
  dest: /data/mirrors/k8s
  # 下载超时时间（单位：秒）
  timeout: 60
  # 重试次数
  retries: 4
  # 重试间隔（单位：秒）
  retry_stagger: 5

# Mirrors Settings
mirrors:
  # NVIDIA Container Toolkit 镜像源配置
  # https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html
  # 官方源
  # https://nvidia.github.io/libnvidia-container
  # 国内源
  # https://mirrors.ustc.edu.cn/libnvidia-container
  nvidia_container:
    rhel:
      baseurl: "https://mirrors.ustc.edu.cn/libnvidia-container/stable/rpm/$basearch"
      gpgcheck: no
      gpgkey: "https://mirrors.ustc.edu.cn/libnvidia-container/gpgkey"
    ubuntu:
      baseurl: "https://mirrors.ustc.edu.cn/libnvidia-container/stable/deb/$(ARCH)"
      gpgkey: "https://mirrors.ustc.edu.cn/libnvidia-container/gpgkey"


# System Settings
system:
  # 系统时区, 可选值请参考 https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  timezone: Asia/Shanghai
  # 强烈建议在生产环境中禁用密码认证, 使用 SSH 密钥认证来提升安全性
  allow_password_authentication: true
  # ssh key path, 当禁用密码认证时, 会自动从该路径读取公钥并添加到目标节点 authorized_keys 文件中
  ssh_key_path: /root/.ssh/id_rsa.pub
  # Kubernetes 通常要求禁用防火墙
  firewalld_enabled: false
  # 仅当集群节点需要进行 SELinux 加固时启用
  selinux_enabled: false
  # ntp_enabled 如果设置为 false, 则节点 NTP 配置将保持不变 (通常由 chronyd 或 systemd-timesyncd 管理)
  ntp_enabled: false
  ntp_servers:
    - "ntp1.aliyun.com iburst"
    - "ntp2.aliyun.com iburst"
    - "ntp3.aliyun.com iburst"
    - "ntp4.aliyun.com iburst"


# Kubernetes Certificates
certificates:
  # 签发集群证书保存目录
  dir: /opt/certs
  # RSA 密钥长度, 2048 or 4096, 当使用 ECC 算法时, 该参数无效
  size: 2048
  # 签发证书的时间, 默认签发10年有限期证书
  day: 3650d
  # 证书加密算法 RSA or ECC
  type: RSA


# High Availability
loadbalance:
  # 负载均衡器IP或VIP
  ip: 10.44.105.100
  # 使用域名访问, 该域名需要在 DNS 中解析到负载均衡器IP或VIP
  # domain_name: apiserver.example.com
  # Kubernetes API Server 负载均衡器监听端口
  port: 6443
  # 需要额外IP访问 API Server 时开启
  # access_domain:
  #   - apiserver.example.com
  # access_ip:
  #   - 101.133.238.222


# https://github.com/etcd-io/etcd
etcd:
  # etcd 安装包下载地址
  download_url: https://files.m.daocloud.io/github.com/etcd-io/etcd/releases/download
  # etcd 版本
  # 应与 kubernetes 中的 SupportedEtcdVersion 保持一致:
  #   https://github.com/kubernetes/kubernetes/blob/v1.36.2/cmd/kubeadm/app/constants/constants.go
  version: v3.6.8
  # etcd 数据目录，如使用多个目录映射同一块数据盘的方式，请勿修改默认目录
  data_dir: /var/lib/etcd
  # 额外参数
  extra_flags:
    # 设置后端数据库可使用最大大小, 最大推荐8G
    quota-backend-bytes: 8589934592
    # Follower 多久没收到心跳就开始选举, 一般为heartbeat-interval × (5～10), 同机房或低延迟建议设置为 1000ms, 跨可用区或网络偶发抖动建议设置为 3000ms
    election-timeout: 3000
    # Leader 向 Follower 发心跳的频率, 同机房或低延迟建议设置为 100ms, 跨可用区或网络偶发抖动建议设置为 200ms
    heartbeat-interval: 200
    # 每 N 次写事务触发一次 MVCC snapshot + compact, 默认 10000 一般够用, 极高频写（大量 Pod / ConfigMap / Lease）, 建议设置为 50000
    snapshot-count: 50000

# https://github.com/kubernetes/kubernetes
kubernetes:
   # kubernetes 二进制安装包下载地址
  download_url: https://files.m.daocloud.io/dl.k8s.io
  # kubernetes 版本
  version: v1.36.2
  # 配置 IPv4 协议栈网络
  ipv4_stack: true
  # 配置 IPv6 协议栈网络
  ipv6_stack: false
  # 集群Pod网段
  pods_subnet: 172.16.0.0/12
  pods_subnet_ipv6: fd85:ee78:d8a6:8607:1::/107
  # 集群Service网段
  service_addresses: 192.168.0.0/16
  service_addresses_ipv6: fd85:ee78:d8a6:8607:2::/112
  # 服务nodeport端口范围
  service_node_port_range: "30000-50000"
  # 节点Pod网段掩码大小
  node_prefix: 25
  node_prefix_ipv6: 120
  # kube-apiserver 组件
  apiserver:
    # 额外参数
    extra_flags:
      default-not-ready-toleration-seconds: 300
      default-unreachable-toleration-seconds: 300
  # kube-controller-manager 组件
  controller_manager:
    # 额外参数
    extra_flags:
      horizontal-pod-autoscaler-sync-period: 30s
  # kube-scheduler 组件
  scheduler:
    # 额外参数
    extra_flags: {}
  # kubelet 组件
  kubelet:
    # 节点最大Pod数量
    max_pods: 110
    # kubelet 数据目录, 如使用多个目录映射同一块数据盘的方式，请勿修改默认目录
    data_dir: /var/lib/kubelet
    # 额外参数
    extra_flags:
      containerLogMaxSize: 200Mi
      containerLogMaxFiles: 10
      evictionPressureTransitionPeriod: 5m0s
      evictionHard:
        imagefs.available: 10%
        memory.available: 500Mi
        nodefs.available: 10%
        nodefs.inodesFree: 5%
  # kube-proxy 组件
  proxy:
    # kube-proxy 模式, 支持 iptables, ipvs, nftables.
    # 从 v1.35.0 开始 ipvs 模式标记废弃，推荐迁移至 nftables 模式
    # https://kubernetes.io/zh-cn/blog/2025/02/28/nftables-kube-proxy/
    mode: nftables
    # 配置kube-proxy的ipvs调度策略
    scheduler: rr
    # 使用 MetalLB, kube-vip 必须设置为 true 才能正常工作
    strict_arp: false
    # kube-proxy 替换为网络插件的代理模式
    replacement: false
    # 额外参数
    extra_flags: {}


# https://github.com/containernetworking/plugins
cniplugins:
  # cni-plugins 安装包下载地址
  download_url: https://files.m.daocloud.io/github.com/containernetworking/plugins/releases/download
  # cni-plugins 版本
  version: v1.9.1


# https://github.com/kubernetes-sigs/cri-tools
critools:
  # cri-tools 安装包下载地址
  download_url: https://files.m.daocloud.io/github.com/kubernetes-sigs/cri-tools/releases/download
  # cri-tools 版本
  version: v1.36.0


# https://github.com/opencontainers/runc
runc:
  # runc 安装包下载地址
  download_url: https://files.m.daocloud.io/github.com/opencontainers/runc/releases/download
  # runc 版本，建议根据containerd版本对应
  # https://github.com/containerd/containerd/blob/v2.3.1/script/setup/runc-version
  version: v1.4.2


# https://github.com/containerd/containerd
containerd:
  # containerd 安装包下载地址
  download_url: https://files.m.daocloud.io/github.com/containerd/containerd/releases/download
  # containerd 版本
  version: 2.3.1
  # containerd 配置文件目录
  cfg_dir: /etc/containerd
  # containerd 持久化数据目录，如使用多个目录映射同一块数据盘的方式，请保持默认目录
  root: "/var/lib/containerd"
  # containerd 临时数据目录
  state: "/run/containerd"
  # containerd oom_score
  oom_score: -999
  grpc:
    max_recv_message_size: 16777216
    max_send_message_size: 16777216
  debug:
    address: ""
    level: "info"
    format: ""
    uid: 0
    gid: 0
  metrics:
    address: ""
    grpc_histogram: false
  cri:
    sandbox_image:
      repo: "registry.aliyuncs.com/google_containers/pause"
      tag: "3.10.2"
    max_container_log_line_size: 16384
    enable_unprivileged_ports: false
    enable_unprivileged_icmp: false
    enable_selinux: false
    disable_apparmor: false
    tolerate_missing_hugetlb_controller: true
    disable_hugetlb_controller: true
    image_pull_progress_timeout: 5m
    enable_cdi: false
  containerd:
    snapshotter: overlayfs
    discard_unpacked_layers: true
  options:
    SystemdCgroup: true
  nri:
    enabled: false
  registry_mirrors:
    - prefix: docker.io
      mirrors:
        - host: https://registry-1.docker.io
          capabilities: ["pull", "resolve"]
          skip_verify: false
        #   ca: ["/etc/certs/mirror.pem"]
        #   client: [["/etc/certs/client.pem", ""],["/etc/certs/client.cert", "/etc/certs/client.key"]]
        # - host: https://registry.kubeop.com
        #   capabilities: ["pull", "resolve", "push"]
        #   header:
        #     # XXX替换为 "用户名:密码" 的base64值, $(echo -n "username:password" | base64)
        #     Authorization: "Basic XXX"
  registry_auth: []
    #- registry: 10.0.0.2:5000
    #  username: user
    #  password: pass
  tracing:
    enabled: false
    endpoint: "http://<victoria-traces>/insert/opentelemetry"
    # 协议，支持grpc和http/protobuf
    protocol: "http/protobuf"
    sampling_ratio: 1.0
    service_name: "containerd"


# Kubernetes Addons
# https://github.com/helm/helm
helm:
  enabled: true
  # helm 安装包下载地址
  download_url: https://files.m.daocloud.io/get.helm.sh
  # helm 版本
  version: v4.2.1


# Network Plugin
# 支持选项: flannel, calico, cilium, none
network_plugin: calico

# https://github.com/flannel-io/flannel
flannel:
  # flannel 版本
  version: v0.28.5
  plugin_version: v1.9.1-flannel1
  # {{flannel.registry}}/flannel-cni-plugin:{{flannel.plugin_version}}
  # {{flannel.registry}}/flannel:{{flannel.version}}
  registry: registry.cn-hangzhou.aliyuncs.com/kubeop
  # "vxlan" or "host-gw"
  network_mode: vxlan
  # 运行参数
  args:
    - "--ip-masq"
    - "--kube-subnet-mgr"
  # 当主机位于同一子网上时启用直接路由
  directRouting: false
  # 传出数据包的所需 MTU，如果未定义，则使用外部接口的 MTU。
  # mtu: 1500
  # 开启nftables模式支持，需确保内核版本>=4.18，并且kube-proxy mode设置为nftables
  nftables_enabled: false

# https://github.com/projectcalico/calico
calico:
  # calico 版本
  version: v3.32.1
  # {{calico.registry}}/kube-controllers:{{calico.version}}
  # {{calico.registry}}/node:{{calico.version}}
  # {{calico.registry}}/cni:{{calico.version}}
  # {{calico.registry}}/typha:{{ calico.version }}
  registry: registry.cn-hangzhou.aliyuncs.com/kubeop
  # "ipip" or "bgp" or "mix"
  network_mode: ipip
  # Valid option: Disabled (default), Enabled
  nftable_mode: Disabled
  # mtu 默认为0，表示自动自动检测
  mtu: 0
  # 可指定网卡interface=eth.*或使用can-reach=网关
  # ip_autodetection_method: "interface=eth.*"
  # ipv6_autodetection_method: "interface=eth.*"

cilium:
  # cilium 安装包下载地址
  download_url: https://files.m.daocloud.io/raw.githubusercontent.com/cilium/charts/master
  # cilium 版本
  version: v1.19.5
  # {{cilium.registry}}/operator-generic:{{cilium.version}}
  # {{cilium.registry}}/cilium:{{cilium.version}}
  registry: registry.cn-hangzhou.aliyuncs.com/kubeop
  # Set extra flags
  extra_flags:
    MTU: 1450
    operator.replicas: 2
    image.repository: "registry.cn-hangzhou.aliyuncs.com/devops-system/cilium"
    image.useDigest: false
    operator.image.repository: "registry.cn-hangzhou.aliyuncs.com/devops-system/operator"
    operator.image.useDigest: false
    routingMode: tunnel   # 路由模式，支持tunnel和native
    autoDirectNodeRoutes: false
    tunnelProtocol: vxlan # 隧道协议，mode=tunnel时必填
    ipam.mode: cluster-pool
    ipam.operator.clusterPoolIPv4PodCIDRList: "{ {{- kubernetes.pods_subnet -}} }"
    ipam.operator.clusterPoolIPv4MaskSize: "{{kubernetes.node_prefix}}"
    kubeProxyReplacement: true
    k8sServiceHost: "{{ loadbalance.ip }}"   # 负载均衡器IP或域名
    k8sServicePort: "{{ loadbalance.port }}" # 负载均衡器端口
    bpf.masquerade: true
    bpf.hostRouting: true
    bpf.ctTcpMax: 1048576
    bpf.ctAnyMax: 524288
    bpf.natMax: 1048576
    bpf.lbMapMax: 131072
    bandwidthManager.enabled: true
    loadBalancer.mode: snat
    loadBalancer.acceleration: best-effort
    envoy.enabled: false
    hubble.enabled: true
    hubble.relay.enabled: false
    hubble.metrics.enabled: "{dns,drop,tcp,flow}"
    resources.requests.cpu: 500m
    resources.requests.memory: 512Mi
    resources.limits.cpu: 5000m 
    resources.limits.memory: 2048Mi
    operator.resources.requests.cpu: 200m
    operator.resources.requests.memory: 256Mi
    operator.resources.limits.cpu: 1000m
    operator.resources.limits.memory: 1024Mi


# Kubernetes Apps
coredns:
  # https://github.com/coredns/coredns
  version: 1.14.4
  # {{coredns.registry}}/coredns:{{coredns.version}}
  registry: registry.cn-hangzhou.aliyuncs.com/kubeop

nodelocaldns:
  enabled: true
  version: 1.26.8
  # {{nodelocaldns.registry}}/k8s-dns-node-cache:{{nodelocaldns.version}}
  registry: registry.cn-hangzhou.aliyuncs.com/kubeop
  ip: "169.254.20.10"
  ip6: "fd00::"

metrics_server:
  # https://github.com/kubernetes-sigs/metrics-server
  enabled: true
  version: v0.8.1
  # {{metrics_server.registry}}/metrics-server:{{metrics_server.version}}
  registry: registry.cn-hangzhou.aliyuncs.com/kubeop

npd:
  # https://github.com/kubernetes/node-problem-detector
  enabled: false
  version: v1.35.2
  # {{npd.registry}}/node-problem-detector:{{npd.version}}
  registry: registry.cn-hangzhou.aliyuncs.com/kubeop

nvidia_device_plugin:
  # https://github.com/NVIDIA/k8s-device-plugin
  enabled: false
  version: v0.19.2
  # {{nvidia_device_plugin.registry}}/k8s-device-plugin:{{nvidia_device_plugin.version}}
  registry: registry.cn-hangzhou.aliyuncs.com/kubeop
