---
dependencies:
  - role: network-plugins/flannel
    when: network_plugin == 'flannel'
    tags:
      - flannel

  - role: network-plugins/calico
    when: network_plugin == 'calico'
    tags:
      - calico

  - role: network-plugins/cilium
    when: network_plugin == 'cilium'
    tags:
      - cilium
