---
- name: Check ansible version
  import_playbook: ansible_version.yml

- name: Pre-installation preparation
  hosts: etcd master worker
  roles:
    - role: checks
      tags: checks

- name: Generate certificates
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - role: certificates
      tags: certificates

- name: System initialization
  hosts: etcd master worker
  roles:
    - role: init
      tags: init

- name: Configure Haproxy + Keepalived
  hosts: haproxy
  roles:
    - role: haproxy
      tags: haproxy
    - role: keepalived
      tags: keepalived

- name: Configure Kubernetes Etcd
  hosts: etcd
  roles:
    - role: etcd
      tags: etcd

- name: Configure Kubernetes Master
  hosts: master
  roles:
    - role: master
      tags: master

- name: Configure Kubernetes Worker
  hosts: master worker
  roles:
    - role: containerd
      tags: containerd
    - role: worker
      tags: worker

- name: Configure Kubernetes Addons
  hosts: master worker
  roles:
    - role: kubernetes-addons
      tags: kubernetes-addons

- name: Configure Network Plugins
  hosts: master
  roles:
    - role: network-plugins
      tags: network-plugins

- name: Configure Kubernetes Apps
  hosts: master
  roles:
    - role: kubernetes-apps
      tags: kubernetes-apps
