---
- name: "Reset Worker"
  hosts: worker
  pre_tasks:
    - name: Reset Confirmation
      pause:
        prompt: "Are you sure you want to reset worker node state? Type 'yes' to reset your worker node."
      register: reset_confirmation_prompt
      run_once: true
      when:
        - not (skip_confirmation | default(false) | bool)
        - reset_confirmation is not defined

    - name: Check confirmation
      fail:
        msg: "Reset confirmation failed"
      when:
        - not reset_confirmation | default(false) | bool
        - not reset_confirmation_prompt.user_input | default("") == "yes"

  roles:
    - role: reset
      tags: reset