---
- name: Calico | Create manifest
  ansible.builtin.template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  with_items:
    - {src: "crds.yaml.j2", dest: "/tmp/calico-crds.yaml"}
    - {src: "calico.yaml.j2", dest: "/tmp/calico.yaml"}
    - {src: "calico-typha.yaml.j2", dest: "/tmp/calico-typha.yaml"}
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  tags:
    - calico
    - calico_yaml

- name: Calico | Apply calico manifest
  ansible.builtin.shell: "kubectl apply -f /tmp/calico-crds.yaml -f /tmp/calico.yaml -f /tmp/calico-typha.yaml"
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  tags:
    - calico
    - calico_install
