---
- name: restart chronyd
  ansible.builtin.systemd:
    name: "{{ 'chronyd' if ansible_os_family in ['RedHat', 'AlmaLinux', 'Rocky', 'TencentOS'] else 'chrony' }}"
    state: restarted
    enabled: yes
    masked: false

- name: restart sshd
  ansible.builtin.systemd:
    name: "{{ 'sshd' if ansible_os_family in ['RedHat', 'AlmaLinux', 'Rocky', 'TencentOS'] else 'ssh' }}"
    state: restarted
    enabled: yes
    masked: false

- name: restart systemd-journald
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted
    enabled: yes
    masked: false
