---
- name: Cilium | Copy helm chart
  ansible.builtin.unarchive:
    src: "{{ download.dest }}/cilium/cilium-{{ cilium.version | replace('v', '') }}.tgz"
    dest: /tmp/
    remote_src: no

- name: Cilium | Build helm command
  ansible.builtin.set_fact:
    helm_set_command: >-
      {% set parts = [] %}
      {% for k, v in cilium.extra_flags.items() %}
        {% if v is string %}
          {% set _ = parts.append(k ~ '="' ~ v ~ '"') %}
        {% else %}
          {% set _ = parts.append(k ~ "=" ~ v) %}
        {% endif %}
      {% endfor %}
      {{ parts | join(",") }}
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true

- name: Cilium | Build helm command
  ansible.builtin.set_fact:
    cilium_helm_cmd: >-
      helm upgrade --install cilium /tmp/cilium --namespace kube-system --set {{ helm_set_command | trim}}
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true

- name: Debug helm command
  ansible.builtin.debug:
    msg: "{{ cilium_helm_cmd }}"
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true

- name: Cilium | install 
  ansible.builtin.command:
    cmd: "{{ cilium_helm_cmd }}"
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
