---
- name: restart etcd
  ansible.builtin.systemd:
    name: etcd
    state: restarted
    daemon_reload: yes
    enabled: yes
  register: etcd_restarted
  notify:
    - wait for etcd up

- name: wait for etcd up
  ansible.builtin.uri:
    url: "https://{%- if kubernetes.ipv4_stack and kubernetes.ipv6_stack -%}{{ ansible_default_ipv4.address }}{%- elif kubernetes.ipv4_stack -%}{{ ansible_default_ipv4.address }}{%- else -%}[{{ ansible_default_ipv6.address }}]{%- endif -%}:2379/health"
    validate_certs: false
    client_cert: "/etc/etcd/pki/etcd-healthcheck-client.pem"
    client_key: "/etc/etcd/pki/etcd-healthcheck-client.key"
  register: result
  until: result.status is defined and result.status == 200
  retries: 60
  delay: 1
  when: etcd_restarted.changed
