---
- name: Reset | stop etcd service
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
  with_items:
    - etcd.service
  failed_when: false
  when: inventory_hostname in groups['etcd']
  tags: 
    - stop_service
  
- name: Reset | stop master service
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
  with_items:
    - kube-apiserver.service
    - kube-controller-manager.service
    - kube-scheduler.service
  failed_when: false
  when: inventory_hostname in groups['master']
  tags: 
    - stop_service

- name: Reset | stop worker service
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
  with_items:
    - kubelet.service
    - kube-proxy.service
  failed_when: false
  when: inventory_hostname in groups['master'] or inventory_hostname in groups['worker']
  tags: 
    - stop_service

- name: Reset | remove etcd services
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /usr/lib/systemd/system/etcd.service
  when: inventory_hostname in groups['etcd']
  register: etcd_services_removed
  tags:
    - services

- name: Reset | remove master services
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /usr/lib/systemd/system/kube-apiserver.service
    - /usr/lib/systemd/system/kube-controller-manager.service
    - /usr/lib/systemd/system/kube-scheduler.service
  when: inventory_hostname in groups['master']
  register: master_services_removed
  tags:
    - services

- name: Reset | remove worker services
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf
    - /etc/sysconfig/kubelet
    - /usr/lib/systemd/system/kubelet.service
    - /usr/lib/systemd/system/kube-proxy.service
  when: inventory_hostname in groups['master'] or inventory_hostname in groups['worker']
  register: worker_services_removed
  tags:
    - services

- name: Reset | systemctl daemon-reload  # noqa no-handler
  ansible.builtin.systemd:
    daemon_reload: true
  when: master_services_removed.changed or worker_services_removed.changed or worker_services_removed.changed

- name: Reset | check if crictl is present
  ansible.builtin.stat:
    path: "/usr/local/bin/crictl"
    get_attributes: no
    get_checksum: no
    get_mime: no
  register: crictl
  tags:
    - containerd

- name: Reset | stop all cri containers
  ansible.builtin.shell: "set -o pipefail && /usr/local/bin/crictl ps -q | xargs -r /usr/local/bin/crictl -t 60s stop"
  args:
    executable: /bin/bash
  register: remove_all_cri_containers
  retries: 5
  until: remove_all_cri_containers.rc == 0
  delay: 5
  when:
    - crictl.stat.exists
  ignore_errors: true
  tags:
    - containerd

- name: Reset | force remove all cri containers
  ansible.builtin.command: "/usr/local/bin/crictl rm -a -f"
  register: remove_all_cri_containers
  retries: 5
  until: remove_all_cri_containers.rc == 0
  delay: 5
  when:
    - crictl.stat.exists
  ignore_errors: true
  tags:
    - containerd

- name: Reset | stop all cri pods
  ansible.builtin.shell: "set -o pipefail && /usr/local/bin/crictl pods -q | xargs -r /usr/local/bin/crictl -t 60s stopp"
  args:
    executable: /bin/bash
  register: remove_all_cri_containers
  retries: 5
  until: remove_all_cri_containers.rc == 0
  delay: 5
  when:
    - crictl.stat.exists
  ignore_errors: true
  tags:
    - containerd

- name: force remove all cri pods
  block:
    - name: force remove all cri pods
      ansible.builtin.command: "/usr/local/bin/crictl rmp -a -f"
      register: remove_all_cri_containers
      retries: 5
      until: remove_all_cri_containers.rc == 0
      delay: 5
      when:
        - crictl.stat.exists
        - ansible_facts.services['containerd.service'] is defined
      tags:
        - containerd

  rescue:
    - name: force remove all cri pods (rescue)
      ansible.builtin.shell: "ip netns list | cut -d' ' -f 1 | xargs -n1 ip netns delete && /usr/local/bin/crictl rmp -a -f"
      ignore_errors: true  # noqa ignore-errors
      changed_when: true
      tags:
        - containerd

- name: Reset | stop containerd
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
  with_items:
    - containerd.service
  failed_when: false
  tags: 
    - containerd

- name: Reset | remove containerd
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /usr/lib/systemd/system/containerd.service
    - /etc/containerd/config.toml
    - /etc/crictl.yaml
    - /usr/local/bin/crictl
  register: containerd_removed
  tags:
    - containerd

- name: Reset | systemctl daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
  when: containerd_removed.changed
  tags:
    - containerd

- name: Reset | gather mounted kubelet dirs
  ansible.builtin.shell: set -o pipefail && mount | grep /var/lib/kubelet/ | awk '{print $3}' | tac
  args:
    executable: /bin/bash
  check_mode: no
  register: mounted_dirs
  failed_when: false
  changed_when: false
  tags:
    - mounts

- name: Reset | unmount kubelet dirs
  ansible.builtin.command: umount -f {{ item }}
  with_items: "{{ mounted_dirs.stdout_lines }}"
  register: umount_dir
  when: mounted_dirs
  retries: 4
  until: umount_dir.rc == 0
  delay: 5
  tags:
    - mounts

- name: Reset | Set IPv4 iptables default policies to ACCEPT
  ansible.builtin.iptables:
    chain: "{{ item }}"
    policy: ACCEPT
  with_items:
    - INPUT
    - FORWARD
    - OUTPUT
  when: flush_iptables | bool and kubernetes.ipv4_stack
  tags:
    - iptables

- name: Reset | Flush iptables
  ansible.builtin.iptables:
    table: "{{ item }}"
    flush: true
  with_items:
    - filter
    - nat
    - mangle
    - raw
  when: flush_iptables | bool and kubernetes.ipv4_stack
  tags:
    - iptables

- name: Reset | Delete IPv4 user-defined chains
  ansible.builtin.command: iptables -X
  when: flush_iptables | bool and kubernetes.ipv4_stack
  tags:
    - iptables

- name: Reset | Set IPv6 ip6tables default policies to ACCEPT
  ansible.builtin.iptables:
    chain: "{{ item }}"
    policy: ACCEPT
    ip_version: ipv6
  with_items:
    - INPUT
    - FORWARD
    - OUTPUT
  when: flush_iptables | bool and kubernetes.ipv6_stack
  tags:
    - ip6tables

- name: Reset | Flush ip6tables
  ansible.builtin.iptables:
    table: "{{ item }}"
    flush: true
    ip_version: ipv6
  with_items:
    - filter
    - nat
    - mangle
    - raw
  when: flush_iptables | bool and kubernetes.ipv6_stack
  tags:
    - ip6tables

- name: Reset | Delete IPv6 user-defined chains
  ansible.builtin.command: ip6tables -X
  when: flush_iptables | bool and kubernetes.ipv6_stack
  tags:
    - ip6tables

- name: Reset | Clear IPVS virtual server table
  ansible.builtin.command: "ipvsadm -C"
  ignore_errors: true
  when:
    - kubernetes.proxy.mode == 'ipvs'

- name: Reset | check kube-ipvs0 network device
  ansible.builtin.stat:
    path: /sys/class/net/kube-ipvs0
    get_attributes: false
    get_checksum: false
    get_mime: false
  register: kube_ipvs0

- name: Reset | Remove kube-ipvs0
  ansible.builtin.command: "ip link del kube-ipvs0"
  when:
    - kubernetes.proxy.mode == 'ipvs'
    - kube_ipvs0.stat.exists

- name: Reset | check nodelocaldns network device
  ansible.builtin.stat:
    path: /sys/class/net/nodelocaldns
    get_attributes: false
    get_checksum: false
    get_mime: false
  register: nodelocaldns_device

- name: Reset | Remove nodelocaldns
  ansible.builtin.command: "ip link del nodelocaldns"
  when:
    - nodelocaldns.enabled | default(false) | bool
    - nodelocaldns_device.stat.exists

- name: Reset | Check whether /var/lib/kubelet directory exists
  ansible.builtin.stat:
    path: /var/lib/kubelet
    get_attributes: false
    get_checksum: false
    get_mime: false
  register: var_lib_kubelet_directory

- name: Reset | Find files/dirs with immutable flag in /var/lib/kubelet
  ansible.builtin.command: lsattr -laR /var/lib/kubelet
  become: true
  register: var_lib_kubelet_files_dirs_w_attrs
  changed_when: false
  no_log: true
  when: var_lib_kubelet_directory.stat.exists

- name: Reset | Remove immutable flag from files/dirs in /var/lib/kubelet
  ansible.builtin.file:
    path: "{{ filedir_path }}"
    state: touch
    attributes: "-i"
    mode: 0644
  loop: "{{ var_lib_kubelet_files_dirs_w_attrs.stdout_lines | select('search', 'Immutable') | list }}"
  loop_control:
    loop_var: file_dir_line
    label: "{{ filedir_path }}"
  vars:
    filedir_path: "{{ file_dir_line.split(' ')[0] }}"
  when: var_lib_kubelet_directory.stat.exists

- name: Reset | delete etcd files and directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/etcd
    - /var/lib/etcd
    - /usr/bin/etcd
    - /usr/bin/etcdctl
    - /usr/bin/etcdutl
  ignore_errors: true  # noqa ignore-errors
  when: inventory_hostname in groups['etcd']
  tags:
    - files

- name: Reset | delete master/worker files and directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ kubernetes.kubelet.data_dir }}"
    - "{{ containerd.root }}"
    - "{{ ansible_env.HOME | default('/root') }}/.kube"
    - "{{ ansible_env.HOME | default('/root') }}/.helm"
    - /etc/kubernetes
    - /var/log/kubernetes
    - /etc/cni
    - /opt/cni
    - /run/flannel
    - /etc/flannel
    - /var/log/pods/
    - /var/lib/cni
    - /var/lib/kube-router
    - /var/lib/calico
    - /etc/NetworkManager/conf.d/calico.conf
    - /etc/NetworkManager/conf.d/k8s.conf
    - /etc/cilium
    - /run/calico
    - /etc/bash_completion.d/kubectl.sh
    - /etc/bash_completion.d/crictl
    - /usr/libexec/kubernetes
    - /etc/containerd/certs.d
  ignore_errors: true  # noqa ignore-errors
  when: inventory_hostname in groups['master'] or inventory_hostname in groups['worker']
  tags:
    - files

- name: Reset | remove kubernetes binary files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /usr/bin/kube-apiserver
    - /usr/bin/kube-controller-manager
    - /usr/bin/kube-scheduler
    - /usr/bin/kubelet
    - /usr/bin/kube-proxy
    - /usr/bin/kubectl
    - /usr/bin/kubeadm
  ignore_errors: true  # noqa ignore-errors
  tags:
    - files

- name: Reset | remove containerd binary files
  ansible.builtin.file:
    path: "/usr/local/bin/{{ item }}"
    state: absent
  with_items:
    - containerd
    - containerd-shim
    - containerd-shim-runc-v1
    - containerd-shim-runc-v2
    - containerd-stress
    - crictl
    - critest
    - ctd-decoder
    - ctr
    - runc
  ignore_errors: true  # noqa ignore-errors
  tags:
    - files

- name: Reset | check vxlan.calico network device
  ansible.builtin.stat:
    path: /sys/class/net/vxlan.calico
    get_attributes: false
    get_checksum: false
    get_mime: false
  register: vxlan
  tags:
    - reset_calico

- name: Reset | remove the network vxlan.calico device created by calico
  ansible.builtin.command: ip link del vxlan.calico
  when: vxlan.stat.exists
  tags:
    - reset_calico

- name: Reset | check dummy0 network device
  ansible.builtin.stat:
    path: /sys/class/net/dummy0
    get_attributes: false
    get_checksum: false
    get_mime: false
  register: dummy0
  tags:
    - reset_calico

- name: Reset | remove the network device created by calico
  ansible.builtin.command: ip link del dummy0
  when: dummy0.stat.exists
  tags:
    - reset_calico

- name: Reset | get and remove remaining routes set by bird
  ansible.builtin.shell: set -o pipefail && ip route show proto bird | xargs -i bash -c "ip route del {} proto bird "
  args:
    executable: /bin/bash
  changed_when: false
  tags:
    - reset_calico

- name: Reset | check and remove devices if still present
  include_tasks: reset_iface.yml
  vars:
    iface: "{{ item }}"
  loop:
    - cilium_host
    - cilium_net
    - cilium_vxlan
  tags:
    - reset_cilium

- name: Reset | check cni network device
  stat:
    path: /sys/class/net/cni0
    get_attributes: false
    get_checksum: false
    get_mime: false
  register: cni
  tags:
    - reset_flannel

- name: Reset | remove the network device created by the flannel
  command: ip link del cni0
  when: cni.stat.exists
  tags:
    - reset_flannel

- name: Reset | check flannel network device
  stat:
    path: /sys/class/net/flannel.1
    get_attributes: false
    get_checksum: false
    get_mime: false
  register: flannel
  tags:
    - reset_flannel

- name: Reset | remove the network device created by the flannel
  command: ip link del flannel.1
  when: flannel.stat.exists
  tags:
    - reset_flannel
