---
- name: "Create cni-plugins directory"
  file:
    path: "/opt/cni/bin/"
    owner: root
    group: root
    mode: 0755
    state: directory
  tags: dir

- name: Get cni-plugins
  get_url:
    url: "https://github.91chifun.workers.dev/https://github.com//containernetworking/plugins/releases/download/{{kubernetes.cni_plugins_version}}/cni-plugins-linux-amd64-{{kubernetes.cni_plugins_version}}.tgz"
    dest: /tmp/

- name: Install cni-plugins
  unarchive:
    src: "/tmp/cni-plugins-linux-amd64-{{kubernetes.cni_plugins_version}}.tgz"
    dest: /opt/cni/bin/
    remote_src: yes
