---
- name: Worker | Install dependency
  ansible.builtin.package:
    name:
      - libnetfilter_cthelper
      - libnetfilter_cttimeout
      - libnetfilter_queue
      - conntrack-tools
      - ipvsadm
      - ipset
      - socat
    state: present
  when:
    - ansible_os_family in ['RedHat', 'AlmaLinux', 'Rocky', 'TencentOS']
  tags: worker_app

- name: Worker | Install dependency
  ansible.builtin.package:
    name:
      - libnetfilter-cthelper0
      - libnetfilter-cttimeout1
      - libnetfilter-queue1
      - libnetfilter-conntrack3
      - conntrack
      - ipvsadm
      - ipset
      - socat
    state: present
  when:
    - ansible_os_family in ["Debian"]
  tags: worker_app

- name: Worker | Check if host has NetworkManager
  ansible.builtin.command: systemctl is-active --quiet NetworkManager.service
  register: networkmanager_enabled
  failed_when: false
  changed_when: false
  check_mode: false
  tags: 
    - networkmanager

- name: Worker | Ensure NetworkManager conf.d dir exists
  ansible.builtin.file:
    path: "/etc/NetworkManager/conf.d"
    state: directory
    recurse: true
  when:
    - networkmanager_enabled.rc == 0
  tags: 
    - networkmanager

- name: Worker | Prevent NetworkManager from managing Calico interfaces (cali*/tunl*/vxlan.calico)
  ansible.builtin.copy:
    content: |
      [keyfile]
      unmanaged-devices=interface-name:cali*;interface-name:tunl*;interface-name:vxlan.calico;interface-name:vxlan-v6.calico;interface-name:wireguard.cali;interface-name:wg-v6.cali
    dest: /etc/NetworkManager/conf.d/calico.conf
    mode: "0644"
  when:
    - networkmanager_enabled.rc == 0
    - network_plugin is defined
    - network_plugin == "calico"
  notify: restart NetworkManager
  tags: 
    - networkmanager

- name: Worker | Prevent NetworkManager from managing K8S interfaces (kube-ipvs0/nodelocaldns)
  when:
    - networkmanager_enabled.rc == 0
  ansible.builtin.copy:
    content: |
      [keyfile]
      unmanaged-devices+=interface-name:kube-ipvs0;interface-name:nodelocaldns
    dest: /etc/NetworkManager/conf.d/k8s.conf
    mode: "0644"
  notify: restart NetworkManager
  tags: 
    - networkmanager

- name: Worker | Enable mod
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - "bridge"
    - "overlay"
    - "br_netfilter"
  tags: worker_mod

- name: Worker | Enable mod for ipvs and iptables
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - "ip_tables"
    - "iptable_filter"
  when: 
    - kubernetes.proxy.mode != 'nftables'
  tags: worker_mod

- name: Worker | Enable mod for ipvs
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - "ip_vs"
    - "ip_vs_rr"
    - "ip_vs_wrr"
    - "ip_vs_lc"
    - "ip_vs_wlc"
    - "ip_vs_sh"
    - "ip_vs_dh"
    - "ip_vs_sed"
    - "ip_vs_nq"
  when:
    - kubernetes.proxy.mode == 'ipvs'
  tags: worker_mod

- name: Worker | Enable conntrack mod < 4.19.0
  community.general.modprobe:
    name: "nf_conntrack_ipv4"
    state: present
  when: ((ansible_os_family in ['RedHat', 'AlmaLinux', 'Rocky'] and ansible_distribution_major_version | int != 8) or ansible_os_family in ['Debian']) and
        ansible_kernel.split('-')[0] is version('4.19.0', '<')
  tags: worker_mod

- name: Worker | Enable conntrack mod > 4.19.0
  community.general.modprobe:
    name: "nf_conntrack"
    state: present
  when: (ansible_os_family in ['RedHat', 'AlmaLinux', 'Rocky'] and ansible_distribution_major_version | int == 8) or
        ansible_kernel.split('-')[0] is version('4.19.0', '>=')
  tags: worker_mod

- name: Worker | Install iptables-nft
  ansible.builtin.package:
    name: iptables-nft
    state: present
  when:
    - ansible_os_family in ['RedHat', 'AlmaLinux', 'Rocky', 'TencentOS']
    - kubernetes.proxy.mode == 'ipvs'
    - not (kubernetes.proxy.replacement | default(false))
  tags:
    - kube_proxy

- name: Worker | Install nftables
  ansible.builtin.package:
    name: nftables
    state: present
  when:
    - kubernetes.proxy.mode == 'nftables'
    - not (kubernetes.proxy.replacement | default(false))
  tags:
    - kube_proxy

- name: Worker | Modprobe Kernel Module for nftables
  community.general.modprobe:
    name: "nf_tables"
    state: present
    persistent: present
  when: 
    - kubernetes.proxy.mode == 'nftables'
    - not (kubernetes.proxy.replacement | default(false))
  tags:
    - kube_proxy

- name: Worker | Set sysctl k8s parameters
  ansible.posix.sysctl:
    sysctl_file: "/etc/sysctl.d/99-k8s.conf"
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: true
    state: present
    reload: yes
  with_items:
    - {name: 'net.netfilter.nf_conntrack_max',value: '2310720' }
    - {name: 'net.bridge.bridge-nf-call-iptables',value: '1' }
    - {name: 'net.bridge.bridge-nf-call-ip6tables',value: '1' }
    - {name: 'net.bridge.bridge-nf-call-arptables',value: '1' }
    - {name: 'net.core.somaxconn',value: '32768' }
    - {name: 'net.core.wmem_max',value: '16777216' }
    - {name: 'net.core.rmem_max',value: '16777216' }
    - {name: 'net.core.netdev_max_backlog',value: '16384' }
    - {name: 'vm.max_map_count',value: '262144' }
    - {name: 'kernel.softlockup_panic',value: '1' }
    - {name: 'kernel.pid_max',value: '4194303' }
    - {name: 'kernel.softlockup_all_cpu_backtrace',value: '1' }
    - {name: 'net.ipv4.neigh.default.gc_thresh2',value: '1024' }
    - {name: 'net.ipv4.neigh.default.gc_thresh3',value: '8192' }
    - {name: 'net.ipv4.tcp_max_syn_backlog',value: '8096' }
    - {name: 'net.ipv4.tcp_wmem',value: '4096 12582912 16777216' }
    - {name: 'net.ipv4.tcp_rmem',value: '4096 12582912 16777216' }
    - {name: 'fs.file-max',value: '2097152' }
    - {name: 'fs.inotify.max_user_watches',value: '524288' }
    - {name: 'fs.inotify.max_queued_events',value: '16384' }
    - {name: 'fs.inotify.max_user_instances',value: '16384' }
    - {name: 'user.max_user_namespaces',value: '0' }
  tags:
    - sysctl
    - k8s_sysctl
    - worker_sysctl

- name: Worker | Create kubernetes directory
  ansible.builtin.file:
    path: "{{ item.line }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  with_items:
    - {line: '/etc/kubernetes/pki'}
    - {line: '/etc/kubernetes/manifests'}
    - {line: "{{ kubernetes.kubelet.data_dir }}"}
  tags: dir

- name: Worker | Create kubelet directory
  ansible.builtin.file:
    path: "/etc/sysconfig"
    owner: root
    group: root
    mode: 0755
    state: directory
  when:
    - ansible_os_family in ["Debian"]
  tags: dir

- name: Worker | Install kubelet
  ansible.builtin.copy:
    src: "{{ download.dest }}/kubernetes/{{ kubernetes.version }}/bin/linux/{%- if ansible_architecture == 'x86_64' -%}amd64{%- else -%}arm64{%- endif -%}/kubelet"
    dest: "/usr/bin/"
    owner: root
    group: root
    mode: 0750
  tags: 
    - kubelet
    - install_worker

- name: Worker | Install kube-proxy
  ansible.builtin.copy:
    src: "{{ download.dest }}/kubernetes/{{ kubernetes.version }}/bin/linux/{%- if ansible_architecture == 'x86_64' -%}amd64{%- else -%}arm64{%- endif -%}/kube-proxy"
    dest: "/usr/bin/"
    owner: root
    group: root
    mode: 0750
  when:
    - not (kubernetes.proxy.replacement | default(false))
  tags: 
    - kube_proxy
    - install_worker

- name: Worker | Distribution kubelet certs
  ansible.builtin.copy:
    src: "{{ certificates.dir }}/ca.pem"
    dest: "/etc/kubernetes/pki/"
    owner: root
    group: root
    mode: 0644
  tags:
    - dis_worker_certs
    - dis_certs
    - kubelet

- name: Worker | Distribution kube-proxy certs
  when:
    - not (kubernetes.proxy.replacement | default(false))
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/kubernetes/pki/"
    owner: root
    group: root
    mode: 0644
  with_items:
    - "{{ certificates.dir }}/{{ ansible_hostname.split('-')[-2:] | join('-') | lower }}/kube-proxy.pem"
    - "{{ certificates.dir }}/{{ ansible_hostname.split('-')[-2:] | join('-') | lower }}/kube-proxy.key"
  tags:
    - dis_worker_certs
    - dis_certs
    - kube_proxy

- name: Worker | Get bootstrap-token-id
  ansible.builtin.shell: "cat {{ certificates.dir }}/token | grep -v '^#' | awk -F '.' '{print $1}'"
  register: token_id
  connection: local
  tags:
    - get_token_id
    - bootstrap_token

- name: Worker | Get bootstrap-token-secret
  ansible.builtin.shell: "cat {{ certificates.dir }}/token | grep -v '^#' | awk -F '.' '{print $2}'"
  register: token_secret
  connection: local
  tags:
    - get_token_secret
    - bootstrap_token

- name: Worker | Distribution kubelet kubeconfig
  ansible.builtin.template:
    src: "bootstrap-kubelet.kubeconfig.j2"
    owner: root
    group: root
    mode: 0640
    dest: "/etc/kubernetes/bootstrap-kubelet.kubeconfig"
  tags:
    - kubelet
    - dis_worker_kubeconfig

- name: Worker | Distribution kube-proxy kubeconfig
  ansible.builtin.template:
    src: "proxy.kubeconfig.j2"
    owner: root
    group: root
    mode: 0640
    dest: "/etc/kubernetes/proxy.kubeconfig"
  when:
    - not (kubernetes.proxy.replacement | default(false))
  tags:
    - kube_proxy
    - dis_worker_kubeconfig

- name: Worker | Distribution kubelet config
  ansible.builtin.template:
    src: "{{ item.src }}"
    owner: root
    group: root
    mode: 0640
    dest: "{{ item.dest }}"
  with_items:
    - {src: "kubelet.conf.j2",dest: "/etc/kubernetes/kubelet.conf" }
    - {src: "10-kubelet.conf.j2",dest: "/etc/sysconfig/kubelet" }
  tags:
    - kubelet
    - dis_worker_config

- name: Worker | Distribution kube-proxy config
  ansible.builtin.template:
    src: "kube-proxy.conf.j2"
    owner: root
    group: root
    mode: 0640
    dest: "/etc/kubernetes/kube-proxy.conf"
  when:
    - not (kubernetes.proxy.replacement | default(false))
  tags:
    - kube_proxy
    - dis_worker_config

- name: Worker | Distribution kubelet system unit
  ansible.builtin.template:
    src: "kubelet.service.j2"
    owner: root
    group: root
    mode: 0644
    dest: "/usr/lib/systemd/system/kubelet.service"
  tags:
    - kubelet
    - dis_worker_systemd

- name: Worker | Distribution kube-proxy system unit
  ansible.builtin.template:
    src: "kube-proxy.service.j2"
    owner: root
    group: root
    mode: 0644
    dest: "/usr/lib/systemd/system/kube-proxy.service"
  when:
    - not (kubernetes.proxy.replacement | default(false))
  tags:
    - kube_proxy
    - dis_worker_systemd

- name: Worker | Check if bootstrap-token exists
  ansible.builtin.shell: kubectl -n kube-system get secret bootstrap-token-{{ token_id.stdout }}
  ignore_errors: true
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  register: bootstrap_token_ready
  tags: bootstrap

- name: Worker | Create bootstrap-token secret
  when: bootstrap_token_ready.rc != 0
  ansible.builtin.shell: kubectl -n kube-system create secret generic bootstrap-token-{{ token_id.stdout }} --type 'bootstrap.kubernetes.io/token' --from-literal description="cluster bootstrap token" --from-literal token-id={{ token_id.stdout }} --from-literal token-secret={{ token_secret.stdout }} --from-literal usage-bootstrap-authentication=true --from-literal usage-bootstrap-signing=true --from-literal auth-extra-groups="system:bootstrappers:default-node-token,system:bootstrappers:worker,system:bootstrappers:ingress"
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  tags: bootstrap

- name: Worker | Check if clusterrolebinding kubelet-bootstrap exists
  ansible.builtin.shell: kubectl get clusterrolebinding kubelet-bootstrap
  ignore_errors: true
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  register: kubelet_bootstrap_ready
  tags: bootstrap

- name: Worker | Create clusterrolebinding kubelet-bootstrap
  when: kubelet_bootstrap_ready.rc != 0
  ansible.builtin.shell: kubectl create clusterrolebinding kubelet-bootstrap --clusterrole=system:node-bootstrapper --group=system:bootstrappers:default-node-token
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  tags: bootstrap

- name: Worker | Check if node-autoapprove-bootstrap exists
  ansible.builtin.shell: kubectl get clusterrolebinding node-autoapprove-bootstrap
  ignore_errors: true
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  register: node_autoapprove_bootstrap_ready
  tags: bootstrap

- name: Worker | Create clusterrolebinding node-autoapprove-bootstrap
  when: node_autoapprove_bootstrap_ready.rc != 0
  ansible.builtin.shell: kubectl create clusterrolebinding node-autoapprove-bootstrap --clusterrole=system:certificates.k8s.io:certificatesigningrequests:nodeclient --group=system:bootstrappers:default-node-token
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  tags: bootstrap

- name: Worker | Check if clusterrolebinding node-autoapprove-certificate-rotation exists
  ansible.builtin.shell: kubectl get clusterrolebinding node-autoapprove-certificate-rotation
  ignore_errors: true
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  register: node_autoapprove_certificate_rotation_ready
  tags: bootstrap

- name: Worker | Create clusterrolebinding node-autoapprove-certificate-rotation
  when: node_autoapprove_certificate_rotation_ready.rc != 0
  ansible.builtin.shell: kubectl create clusterrolebinding node-autoapprove-certificate-rotation --clusterrole=system:certificates.k8s.io:certificatesigningrequests:selfnodeclient --group=system:nodes
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  tags: bootstrap

- name: Worker | Restart kubelet
  ansible.builtin.systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes
    enabled: yes
    masked: false
  tags:
    - kubelet
    - restart_kubelet

- name: Worker | Waiting kubelet starting
  ansible.builtin.wait_for:
    host: "{%- if kubernetes.ipv4_stack and kubernetes.ipv6_stack -%}{{ ansible_default_ipv4.address }}{%- elif kubernetes.ipv4_stack -%}{{ ansible_default_ipv4.address }}{%- else -%}{{ ansible_default_ipv6.address }}{%- endif -%}"
    port: 10250
    delay: 5
    sleep: 2
  tags:
    - kubelet
    - healthcheck

- name: Worker | kubelet health check
  ansible.builtin.uri:
    url: "http://{%- if kubernetes.ipv4_stack and kubernetes.ipv6_stack -%}{{ ansible_default_ipv4.address }}{%- elif kubernetes.ipv4_stack -%}{{ ansible_default_ipv4.address }}{%- else -%}[{{ ansible_default_ipv6.address }}]{%- endif -%}:10248/healthz"
    return_content: yes
    validate_certs: no
  register: kubelet
  failed_when: "'ok' not in kubelet.content"
  tags: healthcheck

- name: Worker | Restart kube-proxy
  ansible.builtin.systemd:
    name: kube-proxy
    state: restarted
    daemon_reload: yes
    enabled: yes
    masked: false
  when:
    - not (kubernetes.proxy.replacement | default(false))
  tags:
    - kube_proxy
    - restart_proxy

- name: Worker | Waiting kube-proxy starting
  ansible.builtin.wait_for:
    host: "{%- if kubernetes.ipv4_stack and kubernetes.ipv6_stack -%}{{ ansible_default_ipv4.address }}{%- elif kubernetes.ipv4_stack -%}{{ ansible_default_ipv4.address }}{%- else -%}{{ ansible_default_ipv6.address }}{%- endif -%}"
    port: 10256
    delay: 5
    sleep: 2
  when:
    - not (kubernetes.proxy.replacement | default(false))
  tags:
    - kube_proxy
    - healthcheck

- name: Worker | kube-proxy health check
  ansible.builtin.uri:
    url: "http://{%- if kubernetes.ipv4_stack and kubernetes.ipv6_stack -%}{{ ansible_default_ipv4.address }}{%- elif kubernetes.ipv4_stack -%}{{ ansible_default_ipv4.address }}{%- else -%}[{{ ansible_default_ipv6.address }}]{%- endif -%}:10256/healthz"
    return_content: yes
    validate_certs: no
    status_code: 200
  register: proxy
  when:
    - not (kubernetes.proxy.replacement | default(false))
  tags:
    - kube_proxy
    - healthcheck

- name: Worker | Check kube-proxy status
  ansible.builtin.command: systemctl is-active kube-proxy
  register: proxy_enabled
  failed_when: false
  changed_when: false
  check_mode: false

- name: Worker | Stop kube-proxy if kubernetes.proxy.replacement enabled
  ansible.builtin.systemd:
    name: kube-proxy
    state: stopped
    daemon_reload: yes
    enabled: no
    masked: false
  when:
    - kubernetes.proxy.replacement | default(false)
    - proxy_enabled.rc == 0
  tags:
    - kube_proxy
    - stop_proxy

- name: Worker | Check whether the control-plane is ready?
  ansible.builtin.shell: "kubectl get node {{ hostvars[inventory_hostname]['hostname'].split('-')[-2:] | join('-') | lower }}"
  register: master_status
  until: '"Ready" in master_status.stdout'
  retries: 5
  delay: 3
  delegate_to: "{{ groups['master'][0] }}"
  when: inventory_hostname in groups['master']
  tags:
    - create_master_label
    - create_master_taint
    - create_label

- name: Worker | Create taint for control-plane
  ansible.builtin.shell: "kubectl taint nodes {{ hostvars[inventory_hostname]['hostname'].split('-')[-2:] | join('-') | lower }} node-role.kubernetes.io/control-plane=:NoSchedule --overwrite"
  delegate_to: "{{ groups['master'][0] }}"
  when: inventory_hostname in groups['master']
  tags:
    - create_master_label
    - create_master_taint
    - create_label

- name: Worker | Create label for control-plane
  ansible.builtin.shell: "kubectl label nodes {{ hostvars[inventory_hostname]['hostname'].split('-')[-2:] | join('-') | lower }} node-role.kubernetes.io/control-plane= --overwrite"
  delegate_to: "{{ groups['master'][0] }}"
  when: inventory_hostname in groups['master']
  tags:
    - create_master_label
    - create_label

- name: Worker | Check whether the worker is ready?
  ansible.builtin.shell: "kubectl get node {{ hostvars[inventory_hostname]['hostname'].split('-')[-2:] | join('-') | lower }}"
  register: worker_status
  until: '"Ready" in worker_status.stdout'
  retries: 5
  delay: 3
  delegate_to: "{{ groups['master'][0] }}"
  when: inventory_hostname in groups['worker']
  tags:
    - create_worker_label
    - create_label

- name: Worker | Create label for worker
  ansible.builtin.shell: "kubectl label nodes {{ hostvars[inventory_hostname]['hostname'].split('-')[-2:] | join('-') | lower }} node-role.kubernetes.io/worker= --overwrite"
  delegate_to: "{{ groups['master'][0] }}"
  when: inventory_hostname in groups['worker']
  tags:
    - create_worker_label
    - create_label

- name: Worker | Create taint for gpu worker
  when: gpu is defined and gpu == 'true'
  ansible.builtin.shell: "kubectl taint nodes {{ hostvars[inventory_hostname]['hostname'].split('-')[-2:] | join('-') | lower }} nvidia.com/gpu=:NoSchedule --overwrite"
  delegate_to: "{{ groups['master'][0] }}"
  tags:
    - create_gpu_taint
    - create_gpu

- name: Worker | Create label for gpu worker
  when: gpu is defined and gpu == 'true'
  ansible.builtin.shell: "kubectl label nodes {{ hostvars[inventory_hostname]['hostname'].split('-')[-2:] | join('-') | lower }} nvidia.com/gpu=true --overwrite"
  delegate_to: "{{ groups['master'][0] }}"
  tags:
    - create_gpu_label
    - create_gpu
