---
- name: Control Plane | Create kubernetes group"
  ansible.builtin.group:
    name: kube
    gid: 200
    system: true
  tags: create_kube_group

- name: Control Plane | Create kubernetes user
  ansible.builtin.user:
    name: kube
    uid: 200
    group: kube
    comment: "Kubernetes User"
    create_home: false
    shell: /sbin/nologin
    system: true
  tags: create_kube_user

- name: Control Plane | Create kubernetes config directory
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  with_items:
    - "~/.kube"
    - "/etc/kubernetes/pki"
  tags: dir

- name: Control Plane | Create kubernetes log directory"
  ansible.builtin.file:
    path: "{{ item }}"
    owner: kube
    group: kube
    mode: 0755
    state: directory
  with_items:
    - "/var/log/kubernetes"
    - "/usr/libexec/kubernetes"
  tags: dir

- name: Control Plane | Install kubectl
  ansible.builtin.copy:
    src: "{{ download.dest }}/kubernetes/{{ kubernetes.version }}/bin/linux/{%- if ansible_architecture == 'x86_64' -%}amd64{%- else -%}arm64{%- endif -%}/kubectl"
    dest: "/usr/bin/"
    owner: root
    group: root
    mode: 0755
  tags: install_kubectl

- name: Control Plane | Install master components
  ansible.builtin.copy:
    src: "{{ download.dest }}/kubernetes/{{ kubernetes.version }}/bin/linux/{%- if ansible_architecture == 'x86_64' -%}amd64{%- else -%}arm64{%- endif -%}/{{ item }}"
    dest: "/usr/bin/"
    owner: root
    group: root
    mode: 0755
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
  tags: install_master

- name: Control Plane | Distribution master certs
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/kubernetes/pki/"
    owner: root
    group: root
    mode: 0644
  with_items:
    - "{{ certificates.dir }}/ca.key"
    - "{{ certificates.dir }}/ca.pem"
    - "{{ certificates.dir }}/sa.key"
    - "{{ certificates.dir }}/sa.pub"
    - "{{ certificates.dir }}/etcd-ca.pem"
    - "{{ certificates.dir }}/{{ ansible_hostname.split('-')[-2:] | join('-') | lower }}/apiserver.key"
    - "{{ certificates.dir }}/{{ ansible_hostname.split('-')[-2:] | join('-') | lower }}/apiserver.pem"
    - "{{ certificates.dir }}/{{ ansible_hostname.split('-')[-2:] | join('-') | lower }}/apiserver-etcd-client.key"
    - "{{ certificates.dir }}/{{ ansible_hostname.split('-')[-2:] | join('-') | lower }}/apiserver-etcd-client.pem"
    - "{{ certificates.dir }}/{{ ansible_hostname.split('-')[-2:] | join('-') | lower }}/apiserver-kubelet-client.key"
    - "{{ certificates.dir }}/{{ ansible_hostname.split('-')[-2:] | join('-') | lower }}/apiserver-kubelet-client.pem"
    - "{{ certificates.dir }}/front-proxy-ca.key"
    - "{{ certificates.dir }}/front-proxy-ca.pem"
    - "{{ certificates.dir }}/{{ ansible_hostname.split('-')[-2:] | join('-') | lower }}/front-proxy-client.key"
    - "{{ certificates.dir }}/{{ ansible_hostname.split('-')[-2:] | join('-') | lower }}/front-proxy-client.pem"
    - "{{ certificates.dir }}/{{ ansible_hostname.split('-')[-2:] | join('-') | lower }}/controller-manager.key"
    - "{{ certificates.dir }}/{{ ansible_hostname.split('-')[-2:] | join('-') | lower }}/controller-manager.pem"
    - "{{ certificates.dir }}/{{ ansible_hostname.split('-')[-2:] | join('-') | lower }}/scheduler.key"
    - "{{ certificates.dir }}/{{ ansible_hostname.split('-')[-2:] | join('-') | lower }}/scheduler.pem"
    - "{{ certificates.dir }}/{{ ansible_hostname.split('-')[-2:] | join('-') | lower }}/admin.key"
    - "{{ certificates.dir }}/{{ ansible_hostname.split('-')[-2:] | join('-') | lower }}/admin.pem"
  tags:
    - dis_master_certs
    - dis_certs

- name: Control Plane | Get bootstrap token id
  ansible.builtin.shell: "cat {{ certificates.dir }}/token | grep -v '^#' | awk -F '.' '{print $1}'"
  register: token_id
  connection: local
  tags:
    - dis_kubectl_kubeconfig
    - dis_master_kubeconfig

- name: Control Plane | Distribution kubectl kubeconfig
  ansible.builtin.template:
    src: "admin.kubeconfig.j2"
    mode: 0600
    dest: "~/.kube/config"
  tags:
    - dis_kubectl_kubeconfig
    - dis_master_kubeconfig

- name: Control Plane | Distribution master kubeconfig
  ansible.builtin.template:
    src: "{{ item.src }}"
    owner: root
    group: root
    mode: 0644
    dest: "{{ item.dest }}"
  with_items:
    - {src: "controller-manager.kubeconfig.j2",dest: "/etc/kubernetes/controller-manager.kubeconfig" }
    - {src: "scheduler.kubeconfig.j2",dest: "/etc/kubernetes/scheduler.kubeconfig" }
  tags: dis_master_kubeconfig

- name: Control Plane | Distribution master config
  ansible.builtin.template:
    src: "{{ item.src }}"
    owner: root
    group: root
    mode: 0644
    dest: "{{ item.dest }}"
  with_items:
    - {src: "kube-apiserver.conf.j2",dest: "/etc/kubernetes/kube-apiserver.conf" }
    - {src: "kube-controller-manager.conf.j2",dest: "/etc/kubernetes/kube-controller-manager.conf" }
    - {src: "kube-scheduler.conf.j2",dest: "/etc/kubernetes/kube-scheduler.conf" }
    - {src: "audit-policy.yaml.j2",dest: "/etc/kubernetes/audit-policy.yaml" }
  tags: dis_master_config

- name: Control Plane | Distribution master systemd unit
  ansible.builtin.template:
    src: "{{ item.src }}"
    owner: root
    group: root
    mode: 0644
    dest: "{{ item.dest }}"
  with_items:
    - {src: "kube-apiserver.service.j2",dest: "/usr/lib/systemd/system/kube-apiserver.service" }
    - {src: "kube-controller-manager.service.j2",dest: "/usr/lib/systemd/system/kube-controller-manager.service" }
    - {src: "kube-scheduler.service.j2",dest: "/usr/lib/systemd/system/kube-scheduler.service" }
  tags: dis_master_systemd

- name: Control Plane | Restart kube-apiserver
  ansible.builtin.systemd:
    name: kube-apiserver
    state: restarted
    daemon_reload: yes
    enabled: yes
    masked: false
  tags: restart_apiserver

- name: Control Plane | Restart kube-controller-manager
  ansible.builtin.systemd:
    name: kube-controller-manager
    state: restarted
    daemon_reload: yes
    enabled: yes
    masked: false
  tags: restart_controller

- name: Control Plane | Restart kube-scheduler
  ansible.builtin.systemd:
    name: kube-scheduler
    state: restarted
    daemon_reload: yes
    enabled: yes
    masked: false
  tags: restart_scheduler

- name: Control Plane | Add kubectl completion
  ansible.builtin.shell: "kubectl completion bash >/etc/bash_completion.d/kubectl.sh"
  tags: dis_kubectl_completion

- name: Control Plane | kubectl bash completion file permissions
  ansible.builtin.file:
    path: "/etc/bash_completion.d/kubectl.sh"
    mode: 0755
    owner: root
    group: root
  tags: dis_kubectl_completion

- name: Control Plane | Waiting for kube-apiserver starting
  ansible.builtin.wait_for:
    host: "{%- if kubernetes.ipv4_stack and kubernetes.ipv6_stack -%}{{ ansible_default_ipv4.address }}{%- elif kubernetes.ipv4_stack -%}{{ ansible_default_ipv4.address }}{%- else -%}{{ ansible_default_ipv6.address }}{%- endif -%}"
    port: 6443
    delay: 5
    sleep: 2
  tags: healthcheck

- name: Control Plane | Waiting for kube-controller-manager starting
  ansible.builtin.wait_for:
    host: "{%- if kubernetes.ipv4_stack and kubernetes.ipv6_stack -%}{{ ansible_default_ipv4.address }}{%- elif kubernetes.ipv4_stack -%}{{ ansible_default_ipv4.address }}{%- else -%}{{ ansible_default_ipv6.address }}{%- endif -%}"
    port: 10257
    delay: 5
    sleep: 2
  tags: healthcheck

- name: Control Plane | Waiting for kube-scheduler starting
  ansible.builtin.wait_for:
    host: "{%- if kubernetes.ipv4_stack and kubernetes.ipv6_stack -%}{{ ansible_default_ipv4.address }}{%- elif kubernetes.ipv4_stack -%}{{ ansible_default_ipv4.address }}{%- else -%}{{ ansible_default_ipv6.address }}{%- endif -%}"
    port: 10259
    delay: 5
    sleep: 2
  tags: healthcheck

- name: Control Plane | Kube-apiserver healthcheck
  ansible.builtin.uri:
    url: "https://{%- if kubernetes.ipv4_stack and kubernetes.ipv6_stack -%}{{ ansible_default_ipv4.address }}{%- elif kubernetes.ipv4_stack -%}{{ ansible_default_ipv4.address }}{%- else -%}[{{ ansible_default_ipv6.address }}]{%- endif -%}:6443/healthz"
    return_content: yes
    validate_certs: no
    client_cert: "/etc/kubernetes/pki/admin.pem"
    client_key: "/etc/kubernetes/pki/admin.key"
  register: apiserver
  failed_when: "'ok' not in apiserver.content"
  tags: healthcheck

- name: Control Plane | Kube-controller-manager healthcheck
  ansible.builtin.uri:
    url: "https://{%- if kubernetes.ipv4_stack and kubernetes.ipv6_stack -%}{{ ansible_default_ipv4.address }}{%- elif kubernetes.ipv4_stack -%}{{ ansible_default_ipv4.address }}{%- else -%}[{{ ansible_default_ipv6.address }}]{%- endif -%}:10257/healthz"
    return_content: yes
    validate_certs: no
  register: controller
  failed_when: "'ok' not in controller.content"
  tags: healthcheck

- name: Control Plane | Kube-scheduler healthcheck
  ansible.builtin.uri:
    url: "https://{%- if kubernetes.ipv4_stack and kubernetes.ipv6_stack -%}{{ ansible_default_ipv4.address }}{%- elif kubernetes.ipv4_stack -%}{{ ansible_default_ipv4.address }}{%- else -%}[{{ ansible_default_ipv6.address }}]{%- endif -%}:10259/healthz"
    return_content: yes
    validate_certs: no
  register: scheduler
  failed_when: "'ok' not in scheduler.content"
  tags: healthcheck
