---
- name: "Download Helm binary"
  get_url:
    url: "{{helm.download_url}}/{{helm.version}}/helm-{{helm.version}}-linux-amd64.tar.gz"
    dest: /tmp/

- name: "Unarchive Helm"
  unarchive:
    src: "/tmp/helm-{{helm.version}}-linux-amd64.tar.gz"
    dest: /tmp/
    copy: no

- name: "Install Helm"
  copy:
    src: "/tmp/linux-amd64/helm"
    dest: "/usr/bin/"
    mode: 0750
    remote_src: yes
