---
- name: Worker | Install dependency
  ansible.builtin.package:
    name:
      - util-linux
      - libseccomp
      - libseccomp-devel
    state: present
  when:
    - ansible_os_family in ['RedHat', 'AlmaLinux', 'Rocky', 'TencentOS']
  tags: containerd_app

- name: Worker | Install dependency
  ansible.builtin.package:
    name:
      - util-linux
      - libseccomp2
    state: present
  when:
    - ansible_os_family in ["Debian"]
  tags: containerd_app

- name: Worker | Install container-selinux
  ansible.builtin.package:
    name: container-selinux
    state: present
  when:
    - ansible_os_family in ['RedHat', 'AlmaLinux', 'Rocky', 'TencentOS']
    - system.selinux_enabled == true
  tags: containerd_app

- name: Worker | Add nvidia-container-toolkit yum repository
  ansible.builtin.yum_repository:
    name: nvidia-container-toolkit
    file: nvidia-container-toolkit
    description: "nvidia-container-toolkit"
    baseurl: "{{ mirrors.nvidia_container.rhel.baseurl }}"
    gpgkey: "{{ mirrors.nvidia_container.rhel.gpgkey }}"
    gpgcheck: "{{ mirrors.nvidia_container.rhel.gpgcheck }}"
    enabled: yes
  when:
    - gpu is defined and gpu == 'true'
    - ansible_os_family in ['RedHat', 'AlmaLinux', 'Rocky', 'TencentOS']
  tags: gpu_runtime

- name: Worker | Add nvidia-container-toolkit apt repository
  block:
    - name: "apt repository | add gpgkey"
      ansible.builtin.get_url:
        url: "{{ mirrors.nvidia_container.ubuntu.gpgkey }}"
        dest: "/tmp/nvidia-container-toolkit-keyring.gpg"
        mode: 0644
    - name: "apt repository | import gpgkey"
      ansible.builtin.shell: "gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg /tmp/nvidia-container-toolkit-keyring.gpg"
      args:
        creates: "/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg"
    - name: "apt repository | add repository"
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] {{ mirrors.nvidia_container.ubuntu.baseurl }} /"
        filename: nvidia-container-toolkit
        state: present
  when:
    - gpu is defined and gpu == 'true'
    - ansible_os_family in ["Debian"]
  tags: gpu_runtime

- name: Worker | Install nvidia-container-runtime
  ansible.builtin.package:
    name: 
      - nvidia-container-runtime
      - nvidia-container-toolkit
    state: present
  when: gpu is defined and gpu == 'true'
  tags: gpu_app

- name: Worker | Install runc
  ansible.builtin.copy:
    src: "{{ download.dest }}/runc/{{ runc.version }}/runc.{%- if ansible_architecture == 'x86_64' -%}amd64{%- else -%}arm64{%- endif -%}"
    dest: "/usr/local/sbin/runc"
    owner: root
    group: root
    mode: 0755
  tags: install_runc

- name: Worker | Create cni directory
  ansible.builtin.file:
    path: "/opt/cni/bin"
    owner: root
    group: root
    mode: 0755
    state: directory
  tags: cni_config

- name: Worker | Install cni
  ansible.builtin.unarchive:
    src: "{{ download.dest }}/cniplugins/{{ cniplugins.version }}/cni-plugins-linux-{%- if ansible_architecture == 'x86_64' -%}amd64{%- else -%}arm64{%- endif -%}-{{ cniplugins.version }}.tgz"
    dest: "/opt/cni/bin/"
    remote_src: no
  tags: install_cni

- name: Worker | Install containerd
  ansible.builtin.unarchive:
    src: "{{ download.dest }}/containerd/v{{ containerd.version }}/containerd-{{ containerd.version }}-linux-{%- if ansible_architecture == 'x86_64' -%}amd64{%- else -%}arm64{%- endif -%}.tar.gz"
    dest: "/usr/local/bin/"
    remote_src: no
    extra_opts:
      - --strip-components=1
  tags: install_containerd
  notify:
    - restart containerd

- name: Worker | Set containerd service
  ansible.builtin.template:
    src: "containerd.service.j2"
    dest: "/usr/lib/systemd/system/containerd.service"
    owner: root
    group: root
    mode: 0644
  tags: containerd_config

- name: Worker | Create containerd data directory
  ansible.builtin.file:
    path: "{{ containerd.root }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  tags: containerd_config

- name: Worker | Create containerd config directory
  ansible.builtin.file:
    path: "{{ containerd.cfg_dir }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  tags: containerd_config

- name: Worker | Set containerd config
  ansible.builtin.template:
    src: "{{ 'config-v2.toml.j2' if containerd.version is version('2.0.0', '>=') else 'config-v1.toml.j2' }}"
    dest: "{{ containerd.cfg_dir }}/config.toml"
    owner: root
    group: root
    mode: "0640"
  tags: containerd_config
  notify:
    - restart containerd

- name: Worker | Configure containerd registries
  block:
    - name: Create registry directories
      ansible.builtin.file:
        path: "{{ containerd.cfg_dir }}/certs.d/{{ item.prefix }}"
        state: directory
        mode: "0755"
      loop: "{{ containerd.registry_mirrors }}"
    - name: Write hosts.toml file
      ansible.builtin.template:
        src: hosts.toml.j2
        dest: "{{ containerd.cfg_dir }}/certs.d/{{ item.prefix }}/hosts.toml"
        mode: "0640"
      loop: "{{ containerd.registry_mirrors }}"
  tags: containerd_config
  notify:
    - restart containerd

- name: Worker | Install cri-tools
  ansible.builtin.unarchive:
    src: "{{ download.dest }}/critools/{{ critools.version }}/crictl-{{ critools.version }}-linux-{%- if ansible_architecture == 'x86_64' -%}amd64{%- else -%}arm64{%- endif -%}.tar.gz"
    dest: "/usr/local/bin/"
    remote_src: no
  tags: install_critools
  notify:
    - Get crictl completion
    - Install crictl completion

- name: Worker | Configure cri-tools
  ansible.builtin.template:
    src: "crictl.yaml.j2"
    dest: "/etc/crictl.yaml"
    owner: root
    group: root
    mode: 0644
  tags: cri_tools
